---

server:
  port: 8765
  
zuul:  
  routes:
    well:
      path: /well/**
      serviceId: well-service
      url: https://www.google.co.ve/
    fields:
      path: /fields/**
      serviceId: fields-service
      url: https://www.facebook.com/
      
      
eureka:
  client: 
    enabled: false