---

server:
    port: 8765
 
zuul:
    prefix: /api
    routes:
        account:
            path: /well/**
            serviceId: well-service
        customer:
            path: /fields/**
            serviceId: fields-service